name: flutter_course_dice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+3

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
